import { type Collection, type Product } from "@/types";

export const fallbackCollections: Collection[] = [
  {
    key: "signature",
    name: "Signature",
    caption: "Everyday refined",
    title: "The Signature Edit",
    description: "Clean silhouettes in premium vegetable-tanned leather.",
    sortOrder: 1,
    isActive: true,
  },
  {
    key: "evening",
    name: "Evening",
    caption: "After dark",
    title: "Evening Atelier",
    description: "Compact clutches and micro bags for curated evenings.",
    sortOrder: 2,
    isActive: true,
  },
  {
    key: "workwear",
    name: "Workwear",
    caption: "Polished utility",
    title: "Workwear Collection",
    description: "Structured totes and laptop carriers with interior organisation.",
    sortOrder: 3,
    isActive: true,
  },
];

export const fallbackProducts: Product[] = [
  {
    id: 1,
    name: "Pearl Tote",
    slug: "pearl-tote",
    sku: "SIG-001",
    subtitle: "Full-grain leather tote, champagne",
    description: "A roomy yet refined everyday tote in buttery full-grain leather.",
    price: 2760000,
    material: "Full-grain leather",
    size: "Large",
    stockQty: 12,
    isActive: true,
    isFeatured: true,
    imageUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop",
    displayImageUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800&auto=format&fit=crop",
    colors: [
      { name: "Champagne", hex: "#d4b896" },
      { name: "Ivory", hex: "#f5f0e8" },
    ],
    tags: ["new", "best"],
    collections: [fallbackCollections[0]],
    category: { name: "Handbags", slug: "handbags" },
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 2,
    name: "Blossom Saddle",
    slug: "blossom-saddle",
    sku: "SIG-002",
    subtitle: "Saddle bag, blush saffiano",
    description: "Structured saddle silhouette with a polished gold clasp.",
    price: 1960000,
    material: "Saffiano leather",
    size: "Medium",
    stockQty: 8,
    isActive: true,
    isFeatured: true,
    imageUrl: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop",
    displayImageUrl: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop",
    colors: [
      { name: "Blush", hex: "#ebc3bf" },
      { name: "Mocha", hex: "#8b6f5e" },
    ],
    tags: ["new"],
    collections: [fallbackCollections[0]],
    category: { name: "Handbags", slug: "handbags" },
    createdAt: "2025-01-02T00:00:00Z",
  },
  {
    id: 3,
    name: "Crescent Clutch",
    slug: "crescent-clutch",
    sku: "EVE-001",
    subtitle: "Evening clutch, gold satin",
    description: "A minimal crescent pouch with a magnetic closure and wrist strap.",
    price: 1280000,
    material: "Satin with leather trim",
    size: "Small",
    stockQty: 15,
    isActive: true,
    isFeatured: true,
    imageUrl: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?q=80&w=800&auto=format&fit=crop",
    displayImageUrl: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?q=80&w=800&auto=format&fit=crop",
    colors: [
      { name: "Gold", hex: "#c9b28a" },
      { name: "Champagne", hex: "#d4b896" },
    ],
    tags: ["best"],
    collections: [fallbackCollections[1]],
    category: { name: "Handbags", slug: "handbags" },
    createdAt: "2025-01-03T00:00:00Z",
  },
  {
    id: 4,
    name: "Studio Tote",
    slug: "studio-tote",
    sku: "WRK-001",
    subtitle: "Laptop tote, pebbled leather",
    description: "Fits a 15\" laptop. Dual interior pockets, antique brass hardware.",
    price: 3400000,
    material: "Pebbled leather",
    size: "Large",
    stockQty: 10,
    isActive: true,
    isFeatured: true,
    imageUrl: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=800&auto=format&fit=crop",
    displayImageUrl: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=800&auto=format&fit=crop",
    colors: [
      { name: "Ink", hex: "#1f1b16" },
      { name: "Champagne", hex: "#d4b896" },
    ],
    tags: ["new", "best"],
    collections: [fallbackCollections[2]],
    category: { name: "Handbags", slug: "handbags" },
    createdAt: "2025-01-04T00:00:00Z",
  },
];
